services:
  client:
    build: ./mne-ui
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./mne-ui:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build: ./mne-server
    ports:
      - "5000:5000"
    environment:
      - DISPLAY=host.docker.internal:0.0
    env_file:
      - .env
    volumes:
      - ./mne-server:/app
      - .${LOCAL_SHARED_DATA_PATH}:${SERVER_SHARED_DATA_PATH}  # Mount shared volume
