services:
  client:
    build: ./mne-ui
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./mne-ui:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build: ./mne-server
    ports:
      - "5000:5000"
    volumes:
      - ./mne-server:/app
